import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navber from "@/components/Navber/Navber";
import Footer from '@/components/Footer/Footer'
import AuthProvider from "./servises/AuthProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Navber />
          {children}
          <div className="flex flex-col justify-end">
            <Footer></Footer>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
